name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable) with retry
        uses: Wandalen/wretry.action@v1.4.9
        with:
          attempt_limit: 5
          attempt_delay: 20000
          action: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Build (release) with retry
        uses: Wandalen/wretry.action@v1.4.9
        with:
          attempt_limit: 3
          attempt_delay: 15000
          command: cargo build --release --locked --verbose

