name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    name: Build release artifacts (${{ matrix.os }} / ${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ''
            use_cross: false
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            ext: ''
            use_cross: true
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: ''
            use_cross: false
          - os: macos-latest
            target: aarch64-apple-darwin
            ext: ''
            use_cross: false
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: '.exe'
            use_cross: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Install cross (Linux cross targets)
        if: ${{ matrix.use_cross }}
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build (release)
        run: |
          if [ "${{ matrix.use_cross }}" = "true" ]; then
            cross build --release --locked --target ${{ matrix.target }}
          else
            cargo build --release --locked --target ${{ matrix.target }}
          fi

      - name: Prepare package
        shell: bash
        run: |
          set -euxo pipefail
          BIN_NAME="ssh-manager"
          TARGET_DIR="target/${{ matrix.target }}/release"
          OUT_DIR="dist"
          mkdir -p "$OUT_DIR"
          BIN_PATH="$TARGET_DIR/$BIN_NAME${{ matrix.ext }}"

          # Create archive name
          VERSION="${GITHUB_REF#refs/tags/}"
          PKG_BASENAME="${BIN_NAME}-${VERSION}-${{ matrix.target }}"

          # Copy binary and license/readme
          mkdir -p "$PKG_BASENAME"
          cp "$BIN_PATH" "$PKG_BASENAME/"
          if [ -f LICENSE ]; then cp LICENSE "$PKG_BASENAME/"; fi
          if [ -f README.md ]; then cp README.md "$PKG_BASENAME/"; fi

          # Archive (zip for Windows, tar.gz otherwise)
          if [[ "${{ matrix.os }}" == windows-latest ]]; then
            7z a "$OUT_DIR/$PKG_BASENAME.zip" "$PKG_BASENAME" > /dev/null
          else
            tar -czf "$OUT_DIR/$PKG_BASENAME.tar.gz" "$PKG_BASENAME"
          fi

          # Checksums
          (cd "$OUT_DIR" && shasum -a 256 * > "${BIN_NAME}-${VERSION}-SHA256SUMS.txt") || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ssh-manager-${{ matrix.target }}
          path: dist/*

  publish:
    name: Publish Release
    needs: build-release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


